export const SERVICES = [
  {
    id: "classic-cut",
    name: "Classic Cut",
    price: 20,
    duration: "30 min",
    description: "Timeless haircut tailored to your style",
    icon: "scissors",
  },
  {
    id: "home-service",
    name: "Home Service",
    price: 35,
    duration: "60 min",
    description: "A fresh cut in the comfort of your home",
    icon: "scissors",
  },
  {
    id: "cut-and-beard",
    name: "Cut & Beard Combo",
    price: 55,
    duration: "55 min",
    description: "Full package — haircut plus beard sculpt",
    icon: "scissors",
  },
  {
    id: "hot-towel-shave",
    name: "Hot Towel Shave",
    price: 30,
    duration: "30 min",
    description: "Traditional straight razor shave with hot towel",
    icon: "scissors",
  },
  {
    id: "kids-cut",
    name: "Kids Cut (under 12)",
    price: 10,
    duration: "25 min",
    description: "Gentle, fun haircut for the little gents",
    icon: "scissors",
  },
];

export const TIME_SLOTS = [
  "9:00 AM",
  "9:30 AM",
  "10:00 AM",
  "10:30 AM",
  "11:00 AM",
  "11:30 AM",
  "12:00 PM",
  "12:30 PM",
  "1:00 PM",
  "1:30 PM",
  "2:00 PM",
  "2:30 PM",
  "3:00 PM",
  "3:30 PM",
  "4:00 PM",
  "4:30 PM",
  "5:00 PM",
  "5:30 PM",
  "6:00 PM",
  "6:30 PM",
];

export const DAYS_OF_WEEK = [
  "Sunday",
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
];
